var Grunt = null,
    configuration = {},
    paths = {};

var Path = require('path');

paths.base = Path.normalize(__dirname);

Grunt = function(grunt) {
	var tasks = [
		'grunt-6to5',
		'johto-require',
		'grunt-add-comment',
	];
	for(var i = 0; i < tasks.length; i++) {
		grunt.loadNpmTasks(tasks[i]);
	}

	require('time-grunt')(grunt);
	var pathOption = getPathOption();

	function getPathOption() {
		var pathOption = false;

		if(grunt.option('path')) {

			pathOption = {};
			pathOption.name = Path.normalize(grunt.option('path')).replace(paths.base, '').slice(1);
			pathOption.extension = Path.extname(grunt.option('path'));
		}

		return pathOption;
	}

	configuration.package = grunt.file.readJSON('package.json');

	configuration.johto_require = {
		'6to5': {
			options: {
				match: 'Symbol|Promise|regeneratorRuntime',
				insert: 'require("6to5/polyfill");'
			},
			files: [{
				expand: true,
				cwd: paths.base,
				src: ( pathOption ? [ pathOption.name.replace('.es6', '.js') ] :  ['lib/**/*.js']),
				dest: paths.base
			}]
		}
	};

	configuration['6to5'] = {
		options: {
			sourceMap: false
		},
		dist: {
			files: [{
				expand: true,
				cwd: paths.base,
				ext: '.js',
				src: ( pathOption ? pathOption.name : ['lib/**/*.es6'] ),
				dest: paths.base
			}]
		}
	};

	configuration.add_comment = {
		common: {
			options: {
				comments: ['Autogenerated, do not edit. All changes will be undone.'],
				prepend: true,
				syntaxes: {
					'.js': '//'
				}
			},
			files: [{
				expand: true,
				cwd: '',
				src: ( pathOption ? [pathOption.name.replace('.es6', '.js')] : ['lib/**/*.js'] ),
				dest: ''
			}]
		}
	};

	grunt.initConfig(configuration);

	grunt.registerTask('es6', ['6to5:dist', 'johto_require:6to5', 'add_comment']);
};

module.exports = Grunt;